### ISSUE TITLE
Class cannot be found?

### ISSUE THREAD

**Issue by mgatchis** [nicolasfl/ProductOptionsConnectorBundle#1]
I'm trying to load this module on 2.3 and I'm getting the following error. 

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Exten
  sionsOptionImporterConnectorBundle" from namespace "Extensions\Bundle\OptionImporterConnectorBundle".
  Did you forget a "use" statement for another namespace? in /opt/bitnami/apps/akeneo/htdocs/app/AppKernel.php:25
  Stack trace:
  #0 /opt/bitnami/apps/akeneo/htdocs/app/AppKernel.php(34): AppKernel->registerProjectBundles()
  #1 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(494): AppKern
  el->registerBundles()
  #2 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(134): Symfony
  \Component\HttpKernel\Kernel->initializeBundles()
  #3 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.ph
  p(64): Symfony\Component\HttpKernel\Kernel->boot()
  #4 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfo
  ny\Bundle\FrameworkBund in /opt/bitnami/apps/akeneo/htdocs/app/AppKernel.php on line 25`

Good chance I messed something up but, when declaring the bundle in `app/AppKernel.php` I've changed:

`$bundles[] = new \Extensions\Bundle\OptionImporterConnectorBundle\ExtensionsOptionImporterConnectorBundle()`

to:

`new \Extensions\Bundle\OptionImporterConnectorBundle\ExtensionsOptionImporterConnectorBundle(),`

This seemed to work fine with the mapping bundle but I can't seem to crack this one. 

Any suggestions? - Thank you!

**Comment by nicolasfl** [comment]
Hi, 
Thank you for contacting me :)
Try to add the following line to the registerProjectBundles() function in AppKernel.php : 
new Extensions\Bundle\OptionImporterConnectorBundle\ExtensionsOptionImporterConnectorBundle()

**Comment by mgatchis** [comment]
I appreciate the reply. That's the exact line I entered as you'll see above. I tried every variation I could in terms of leading backslashes and trailing commas. - I've attached both my AppKernel.php file and my terminal commands 

I am using Akeneo CE 2.3.22. Can you please confirm whether or not you've tested with this version or not?

Here is my entire AppKernel.php file:
`<?php

use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\HttpKernel\Kernel;

/**
 * PIM AppKernel
 *
 * @author    Nicolas Dupont <nicolas@akeneo.com>
 * @copyright 2013 Akeneo SAS (http://www.akeneo.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class AppKernel extends Kernel
{
    /**
     * Registers your custom bundles
     *
     * @return array
     */
    protected function registerProjectBundles()
    {
        return [
            new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
            new \Extensions\Bundle\MappingConnectorBundle\ExtensionsMappingConnectorBundle(),
            // new \Extensions\Bundle\OptionImporterConnectorBundle\ExtensionsOptionImporterConnectorBundle(),
            new Extensions\Bundle\OptionImporterConnectorBundle\ExtensionsOptionImporterConnectorBundle()
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function registerBundles()
    {
        $bundles = $this->registerProjectBundles();

        if (in_array($this->getEnvironment(), array('dev', 'test', 'behat'))) {
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
            // $bundles[] = new \Extensions\Bundle\OptionImporterConnectorBundle\ExtensionsOptionImporterConnectorBundle();
        }

        $bundles = array_merge(
            $this->getSymfonyBundles(),
            $this->getOroDependencies(),
            $this->getOroBundles(),
            $this->getPimDependenciesBundles(),
            $this->getPimBundles(),
            $bundles
        );

        return $bundles;
    }

    /**
     * {@inheritdoc}
     */
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->getRootDir() . '/config/config_' . $this->getEnvironment() . '.yml');

        if (is_file($file = $this->getRootDir() . '/config/config_' . $this->getEnvironment() . '_local.yml')) {
            $loader->load($file);
        }
    }

    /**
     * Bundles coming from the PIM
     *
     * @return array
     */
    protected function getPimBundles()
    {
        return [
            // BAP overriden bundles
            new Pim\Bundle\FilterBundle\PimFilterBundle(),
            new Pim\Bundle\NavigationBundle\PimNavigationBundle(),
            new Pim\Bundle\UserBundle\PimUserBundle(),

            // PIM bundles
            new Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle(),
            new Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle(),
            new Pim\Bundle\ApiBundle\PimApiBundle(),
            new Pim\Bundle\CatalogBundle\PimCatalogBundle(),
            new Pim\Bundle\CatalogVolumeMonitoringBundle\PimCatalogVolumeMonitoringBundle(),
            new Pim\Bundle\CommentBundle\PimCommentBundle(),
            new Pim\Bundle\ConnectorBundle\PimConnectorBundle(),
            new Pim\Bundle\DashboardBundle\PimDashboardBundle(),
            new Pim\Bundle\DataGridBundle\PimDataGridBundle(),
            new Pim\Bundle\EnrichBundle\PimEnrichBundle(),
            new Pim\Bundle\ImportExportBundle\PimImportExportBundle(),
            new Pim\Bundle\InstallerBundle\PimInstallerBundle(),
            new Pim\Bundle\LocalizationBundle\PimLocalizationBundle(),
            new Pim\Bundle\NotificationBundle\PimNotificationBundle(),
            new Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle(),
            new Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle(),
            new Pim\Bundle\UIBundle\PimUIBundle(),
            new Pim\Bundle\VersioningBundle\PimVersioningBundle(),
        ];
    }

    /**
     * Bundles required by the PIM
     *
     * @return array
     */
    protected function getPimDependenciesBundles()
    {
        return [
            new Akeneo\Bundle\ElasticsearchBundle\AkeneoElasticsearchBundle(),
            new Akeneo\Bundle\BatchBundle\AkeneoBatchBundle(),
            new Akeneo\Bundle\BatchQueueBundle\AkeneoBatchQueueBundle(),
            new Akeneo\Bundle\BufferBundle\AkeneoBufferBundle(),
            new Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle(),
            new Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle(),
            new Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle(),
            new Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle(),
            new FOS\OAuthServerBundle\FOSOAuthServerBundle(),
            new Oneup\FlysystemBundle\OneupFlysystemBundle(),
        ];
    }

    /**
     * Bundles coming from Symfony Standard Framework.
     *
     * @return array
     */
    protected function getSymfonyBundles()
    {
        return [
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
        ];
    }

    /**
     * * Bundles required by Oro Platform
     *
     * @return array
     */
    protected function getOroDependencies()
    {
        return [
            new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle(),
            new Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle(),
            new FOS\JsRoutingBundle\FOSJsRoutingBundle(),
            new FOS\RestBundle\FOSRestBundle(),
            new JMS\SerializerBundle\JMSSerializerBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Liip\ImagineBundle\LiipImagineBundle(),
        ];
    }

    /**
     * Bundles coming from Oro Platform
     *
     * @return array
     */
    protected function getOroBundles()
    {
        return [
            new Oro\Bundle\AsseticBundle\OroAsseticBundle(),
            new Oro\Bundle\ConfigBundle\OroConfigBundle(),
            new Oro\Bundle\DataGridBundle\OroDataGridBundle(),
            new Oro\Bundle\FilterBundle\OroFilterBundle(),
            new Oro\Bundle\SecurityBundle\OroSecurityBundle(),
            new Oro\Bundle\TranslationBundle\OroTranslationBundle(),
            new Oro\Bundle\UserBundle\OroUserBundle(),
        ];
    }

    /**
     * @return string
     */
    public function getRootDir(): string
    {
        return __DIR__;
    }

    /**
     * @return string
     */
    public function getCacheDir(): string
    {
        return dirname(__DIR__)
            . DIRECTORY_SEPARATOR
            . 'var'
            . DIRECTORY_SEPARATOR
            . 'cache'
            . DIRECTORY_SEPARATOR
            . $this->getEnvironment();
    }

    /**
     * @return string
     */
    public function getLogDir(): string
    {
        return dirname(__DIR__) . DIRECTORY_SEPARATOR . 'var' . DIRECTORY_SEPARATOR . 'logs';
    }
}
`

And here is my terminal log:
I indicated where I updated my AppKernel.php file with
`// UPDATED AppKernel.php FILE HERE //`

`bitnami@htdocs$ composer require nicolas-souffleur/option-importer-connector
Using version ^1.0 for nicolas-souffleur/option-importer-connector              ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                   Nothing to install or update
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug
 // true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ---------------------------------- ------------------
      Bundle                             Method / Error
 --- ---------------------------------- ------------------
  ✔   FOSJsRoutingBundle                 relative symlink
  ✔   OroAsseticBundle                   relative symlink
  ✔   OroConfigBundle                    relative symlink
  ✔   PimNavigationBundle                relative symlink
  ✔   PimUserBundle                      relative symlink
  ✔   PimAnalyticsBundle                 relative symlink
  ✔   PimDashboardBundle                 relative symlink
  ✔   PimDataGridBundle                  relative symlink
  ✔   PimEnrichBundle                    relative symlink
  ✔   PimImportExportBundle              relative symlink
  ✔   PimNotificationBundle              relative symlink
  ✔   PimReferenceDataBundle             relative symlink
  ✔   PimUIBundle                        relative symlink
  ✔   PimCustomEntityBundle              relative symlink
  ✔   ExtensionsMappingConnectorBundle   relative symlink
 --- ---------------------------------- ------------------


 [OK] All assets were successfully installed.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::removeSymfonyStandardFiles
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
> @php bin/console fos:js-routing:dump --target=web/js/routes.js
Dumping exposed routes.

[file+] web/js/routes.js
> Pim\Bundle\InstallerBundle\ComposerScripts::copyUpgradesFiles
Copying migration folder from Akeneo PIM dependency to standard version.
Done.

// UPDATED AppKernel.php FILE HERE //

bitnami@htdocs$ keno cache:clear
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ExtensionsOptionImporterConnectorBundle" from namespace "Extensions\Bundle\OptionImporterConnectorBundle".
Did you forget a "use" statement for another namespace? in /opt/bitnami/apps/akeneo/htdocs/app/AppKernel.php:26
Stack trace:
#0 /opt/bitnami/apps/akeneo/htdocs/app/AppKernel.php(35): AppKernel->registerProjectBundles()
#1 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(494): AppKernel->registerBundles()
#2 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(134): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#4 /opt/bitnami/apps/akeneo/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBund in /opt/bitnami/apps/akeneo/htdocs/app/AppKernel.php on line 26`

Very much appreciate your modules. Unfortunately, this is the one I need the most. 

Thanks again for your help in advance!

**Comment by nicolasfl** [comment]
Yes, this extension have been developed for the 2.3 version.
You're error is not a version issue, in fact it looks like Symfony can't
find the module. Can you confirm me those points :
- the module is present in
vendor/nicolas-souffleur/option-importer-connector
- the file Extensions optioning otter connector bundle.php is present too

**Comment by mgatchis** [comment]
Ok.. I figured it out.. Your composer repo is still pulling from a previous tree. Looks like you changed up some file structuring and updated the module entry name on Dec. 5th.

The include from app/AppKernel.php for this current tree is shown correctly in your instructions but if you require the package from current composer repo, you need to include it from app/AppKernel.php using:

ExtensionsProductOptionsConnectorBundle.php

I imagine you'd just need to update your packagist.org repo to call from the newest github repo.

Anyway... Thanks for the code and the help! You rock!

**Comment by nicolasfl** [comment]
Glad that you resolved it and thank you for telling me about this issue.
I'll fix that as soon as possible.
Don't hesitate if you have any other question :)
